### ISSUE TITLE
Existing tag structures are not maintained when copying pages.

### ISSUE THREAD

**Issue by chrisjpatty** [Hopding/pdf-lib#402] opened 2020-04-09 21:04 UTC
Hi, I've been evaluating pdf-lib to see if it will work for my project and I've run into an issue I thought I'd report. When loading a PDF that has been externally "tagged" for accessibility, the tag structure is maintained if the PDF is immediately exported to file without any modifications, however, when copying pages which contain tagged structures into pdf, the tags for the copied pages are lost.

**Comment by Hopding** [comment] 2020-04-11 23:25
Hello @chrisjpatty!

Thanks for reporting this. The issue you're encountering has the same root cause as https://github.com/Hopding/pdf-lib/issues/218, https://github.com/Hopding/pdf-lib/issues/341, and https://github.com/Hopding/pdf-lib/issues/159.

**Comment by Hopding** [comment] 2020-09-20 22:27
Closed in favor of other issues that track the same root cause. I'll probably create a new parent issue to track this in the future.

**Closed** 2020-09-20 22:26 UTC
