### ISSUE TITLE
Pdf content is getting scrambled after embedding the image

### ISSUE THREAD

**Issue by sanjeet-leewayhertz** [Hopding/pdf-lib#220] opened 2019-10-17 12:11 UTC
Hi
After embedding the image pdf is getting scrambled. Below is the example, how the pdf becomes It's happening only some selected pdfs. I have attached that pdf too. Please help me to fix this.
![Screen Shot 2019-10-17 at 5 36 38 PM](https://user-images.githubusercontent.com/53079105/67007357-d5c2fe00-f104-11e9-8374-1490ebf23ada.png)

[20190718.pdf](https://github.com/Hopding/pdf-lib/files/3739145/20190718.pdf)

Thanks

**Comment by Hopding** [comment] 2019-10-17 13:12
Hello @sanjeet-leewayhertz! I'm unable to reproduce the issue. I used the following script to load the PDF you shared and add a JPG image to it. The resulting PDF looks just fine, and does not appear to be scrambled at all.
```js
import fs from 'fs';
import { PDFDocument } from 'pdf-lib';

(async () => {
  const pdfDoc = await PDFDocument.load(
    fs.readFileSync('20190718.pdf'),
  );

  const img = await pdfDoc.embedJpg(
    fs.readFileSync('assets/images/cat_riding_unicorn.jpg'),
  );

  pdfDoc.getPages()[0].drawImage(img, img.scale(0.1));

  const pdfBytes = await pdfDoc.save();

  fs.writeFileSync('./out.pdf', pdfBytes);
})();
```

Page 1 of [out.pdf](https://github.com/Hopding/pdf-lib/files/3739322/out.pdf):
-----
![out](https://user-images.githubusercontent.com/10351828/67010329-0aa66500-f0b3-11e9-966b-cb54d10a8aaa.png)
-----

In addition to the PDF you provided, would you please share a script and image that I can use to reproduce the issue? Also, what environment are you running pdf-lib in? E.g. Node, browser, React Native, etc...

**Comment by sanjeet-leewayhertz** [comment] 2019-10-17 13:33
Hi @Hopding 
I am using the Node environment. And it's weird same pdf if I open through chrome it's appeared scrambled. And if we open it through any pdf viewer then it appears correct. Here is the screenshot of the same pdf(Opened in chrome browser) that you attached.
![Screen Shot 2019-10-17 at 6 58 56 PM](https://user-images.githubusercontent.com/53079105/67013301-7bc83580-f110-11e9-99d5-8f043dbd338f.png)

Thanks

**Comment by Hopding** [comment] 2019-10-17 20:47
I was able to find the issue. It is due to a bug in the page `Resources` normalization code. It only surfaces in documents with a specific page tree structure. And the resulting PDF files are displayed with binary jargon in certain readers (e.g. Chrome and Acrobat), but not others (e.g. macOS's Preview).

I'm working on a fix. I hope to have it released in the coming days.

**Comment by sanjeet-leewayhertz** [comment] 2019-10-18 08:16
Thanks, @Hopding for the quick reply. I will wait for the fix.

**Comment by Hopding** [comment] 2019-10-19 14:25
Version [`1.2.1`](https://www.npmjs.com/package/pdf-lib/v/1.2.1) is now published. It contains the fix for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.2.1).

You can install this new version with npm:

```
npm install pdf-lib@1.2.1
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.2.1/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.2.1/dist/pdf-lib.min.js

**Closed by Hopding** 2019-10-19 14:25 UTC
