### ISSUE TITLE
Calling page.drawText() with a font blows up size of pdf document

### ISSUE THREAD

**Issue by thebenlamm** [Hopding/pdf-lib#226] opened 2019-10-24 21:51 UTC
When calling `page.drawText()` more than ~470 times the size of the final PDF suddenly blows up. Here is the code to replicate:
```
const fs = require('fs'),
      { PDFDocument, StandardFonts } = require('pdf-lib');

const runTest = async () => {
  const originalPdfBytes = fs.readFileSync('500-blank-pages.pdf');
  const pdfDoc = await PDFDocument.load(originalPdfBytes);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  for (var i = 0; i < 500; i++) {
    const page = pdfDoc.getPages()[i];
    page.drawText(`${i}`, { x: 400, y: 400, font });
  }
  const pdfBytes = await pdfDoc.save();
  fs.writeFileSync('documents/output.pdf', pdfBytes);
}

runTest();
```

I start with a pdf consisting of 500 empty pages (77 KB). If I call `page.drawText()` 450 times the total size of the output pdf is ~250 KB. However starting from around the 470 mark the output pdf suddenly jumps to ~3.3 MB.

The work around is to set the font on the page level with `page.setFont(font)` instead of setting the font on each call to `page.drawText()`.

**Comment by Hopding** [comment] 2019-12-23 14:47
Hello @thebenlamm! I'm unable to reproduce the issue. I created a script that incrementally draws text on a page and then saves the document, recording its size at each iteration:
```js
import fs from 'fs';
import { PDFDocument, StandardFonts } from 'pdf-lib';

const makeWithEmptyPages = async (numPages: number) => {
  const pdfDoc = await PDFDocument.create();
  for (let i = 0; i < numPages; i++) {
    pdfDoc.addPage();
  }
  return pdfDoc.save();
};

(async () => {
  const originalPdfBytes = await makeWithEmptyPages(500);

  const pdfDoc = await PDFDocument.load(originalPdfBytes);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const sizes = [];
  for (let i = 0; i < 500; i++) {
    const page = pdfDoc.getPages()[i];
    page.drawText(`${i}`, { x: 400, y: 400, font });
    const bytes = await pdfDoc.save();
    sizes.push([String(i + 1), String(bytes.length)]);
  }

  const csv = [['Pages', 'Bytes']]
    .concat(sizes)
    .map((row) => row.join(', '))
    .join('\n');

  fs.writeFileSync('sizes.csv', csv);
})();
```
Here's the resulting `sizes.csv` file: [sizes.csv.txt](https://github.com/Hopding/pdf-lib/files/3995289/sizes.csv.txt) (GitHub requires the `.txt` extension 🙄).

And here's a visualization of the data:
![bytes_vs_pages](https://user-images.githubusercontent.com/10351828/71363840-09386380-2560-11ea-8c78-8d41773a9d0c.png)

As you can see, the size of the PDF grows linearly with the number of draw text calls. I do not see the exponential jump that you are describing. (Note that the `Pages` axis is really the number of `drawText()` calls. All iterations have 500 pages. I just labelled it poorly.)

Can you see anything incorrect about the script I'm using here? If not, perhaps the issue has something to do with the specific PDF you are starting with? If so, please feel free to share it and I'll try again to reproduce the issue.

**Comment by Hopding** [comment] 2020-01-01 13:54
@thebenlamm @duyduong112 I'm going to close this issue for now, as I cannot reproduce the issue. But please feel free to reopen it if you'd like to dig into this further!

**Closed by Hopding** 2020-01-01 13:54 UTC

**Comment by thebenlamm** [comment] 2020-02-11 23:01
@Hopding Modified your script a tiny bit to use an existing 500 page pdf ([blank500.pdf](https://github.com/Hopding/pdf-lib/files/4188937/blank500.pdf)) instead of generating a new one.

Only difference now is
`const originalPdfBytes = fs.readFileSync('./documents/blank500.pdf');`

When I run your script with this pdf my graph looks like this:

![exponential_graph](https://user-images.githubusercontent.com/5175102/74287207-63031180-4cf7-11ea-8cf5-94cbd910b642.png)

Here is the resulting csv file [sizes_exponential.csv.txt](https://github.com/Hopding/pdf-lib/files/4188976/sizes_exponential.csv.txt)


However if I update the code to add the font on the page level I get a mostly linear line like you got above.
```
const page = pdfDoc.getPages()[i];
page.setFont(font);
page.drawText(`${i}`, { x: 400, y: 400 });
const bytes = await pdfDoc.save();
sizes.push([String(i + 1), String(bytes.length)]);
```

The only thing I can think of is that because blank500.pdf is PDF v1.3 it is causing some sort of issue.

**Comment by Hopding** [comment] 2020-03-07 16:38
I did a bit more testing on this. I'm still not sure what exactly is causing the problem yet. But my best guess right now is some weird interplay between object streams, `pako`'s deflation, and the number of objects in the document.

I ran 4 variations of the script using your `blank500.pdf` document:

```js
// Test Types:
// 1: No object streams with font key
// 2: No object streams with font method
// 3: Object streams with font key
// 4: Object streams with font method

(async () => {
  const originalPdfBytes = fs.readFileSync('/Users/user/Desktop/blank500.pdf');

  const pdfDoc = await PDFDocument.load(originalPdfBytes);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const sizes = [];
  for (let i = 0; i < 500; i++) {
    console.log('Iteration:', i);
    const page = pdfDoc.getPages()[i];

    /********** Choose one test type below ***********/
    // Test Type 1
    page.drawText(`${i}`, { x: 400, y: 400, font });
    const bytes = await pdfDoc.save({ useObjectStreams: false });

    // Test Type 2
    page.setFont(font);
    page.drawText(`${i}`, { x: 400, y: 400 });
    const bytes = await pdfDoc.save({ useObjectStreams: false });

    // Test Type 3
    page.drawText(`${i}`, { x: 400, y: 400, font });
    const bytes = await pdfDoc.save({ useObjectStreams: true });

    // Test Type 4
    page.setFont(font);
    page.drawText(`${i}`, { x: 400, y: 400 });
    const bytes = await pdfDoc.save({ useObjectStreams: true });
    /*************************************************/

    sizes.push([String(i + 1), String(bytes.length)]);
  }

  const csv = [['Pages', 'Bytes']]
    .concat(sizes)
    .map((row) => row.join(', '))
    .join('\n');

  fs.writeFileSync('sizes.csv', csv);
})();
```

Here's the merged version of all 4 `sizes.csv` files: [merged-sizes.csv.txt](https://github.com/Hopding/pdf-lib/files/4302136/merged-sizes.csv.txt)

And here's a plot: ![merged_bytes_vs_pages](https://user-images.githubusercontent.com/10351828/76147220-923f4100-605f-11ea-80e0-37ff0ac2cb1d.png)

As you can see, the two variants that do not use object streams are, as expected, much larger. And the two variants that do use them are much smaller, even with the unexpected jump you've observed in the Test 3 variant.

I'll continue looking into this as I have time.

**Comment by theprogramsam** [comment] 2025-07-03 15:58
I'm experiencing a 700KB 1500 Blank page document when adding the same text on all pages that is 67 characters in length, the PDF jumps from 700KB to 15MB. This is nearly a 15x increase which seems like something isn't working right.

```javascript
for (let i = 0; i < pageages.length; i++) {
  page.drawText(headerText, {
     x: x,
     y: y,
    size: 6,
    font: embedFontCourier
  });
}
```

Why would this be even with an embedded font?

[numbered_pages_1500.pdf](https://github.com/user-attachments/files/21041075/numbered_pages_1500.pdf)
