### ISSUE TITLE
Layer names lost when embedding pdf

### ISSUE THREAD

**Issue by mattgaspar** [Hopding/pdf-lib#521] opened 2020-07-09 06:06 UTC
I'm trying to take an existing pdf (template) and add a full page image as the lowest layer (background) and some text to the top.
From reading other issues it appears content can only be added on top of other content.
So I'm creating a new doc, drawing the jpg image and then drawing the pdf template on top and then drawing some text.
This is working but when I open the new pdf in Illustrator the original labeled layers are turned into a bunch of generic "Clip Groups" and lose all the labels and organization.

Is there any way to maintain the layers and names when embedding a pdf?

FYI - I encountered the same issue with HummusJS which is why I'm trying this library! (And since HummusJS is end of support)
This library seems to be easier to use and with much better documentation too, Thanks!

Layers from original PDF
![image](https://user-images.githubusercontent.com/811116/87002713-11a86280-c16f-11ea-9f5d-952dcfb4b791.png)

After embedding with pdf-lib
![image](https://user-images.githubusercontent.com/811116/87002750-25ec5f80-c16f-11ea-9ccd-afd39a49a0f9.png)

**Comment by Hopding** [comment] 2020-09-28 22:27
Hello @mattgaspar!

Thanks for reporting this. The issue you're encountering has the same root cause as https://github.com/Hopding/pdf-lib/issues/218, https://github.com/Hopding/pdf-lib/issues/341, and https://github.com/Hopding/pdf-lib/issues/159.

**Comment by Hopding** [comment] 2020-09-28 22:28
Closed in favor of other issues that track the same root cause. I'll probably create a new parent issue to track this in the future.

**Closed by Hopding** 2020-09-28 22:27 UTC
