### ISSUE TITLE
PDF parsing errors with numerous documents

### ISSUE THREAD

**Issue by rernens** [Hopding/pdf-lib#476] opened 2020-06-08 12:31 UTC
Hi,

We have build an application that allows users to upload documents ( pdfs and/or images )  that are than merged together before being handled by support professionals ( unemployement processing ).
We are using various libraries to address various issues and your library is among them.
We use it in a node worker to load the uploaded pdfs, determine if they are owner protected, unprotect them with qpdf and then merge them in a single final pdf with all the other pdfs uploaded.
But we face numerous parsing errors that are preventing us to process uploaded documents despite the fact that Acrobat and other viewers ( ie pdf.js ) have no issues to open them.
We have many documents that we can provide as examples or parsing failures.
let us know how you want to proceed as such documents are of confidential nature.
Thanks for your help.

**Comment by Hopding** [comment] 2020-06-14 23:10
Hello @rernens!

If you like, email me a couple documents at andrew.dillon.j@gmail.com and I will take a look at what's causing the parser to fail.

**Comment by Hopding** [comment] 2020-09-20 19:21
Apologies for the late follow-up, but I don't believe I ever received any documents. So I'm unable to reproduce or troubleshoot the parsing errors. 

I'm going to close this issue for now. But I would very much like to investigate the problem further. So please feel free to reopen it if you're still having trouble and can privately share one of these documents with me!

**Closed by Hopding** 2020-09-20 19:21 UTC
