### ISSUE TITLE
Error: Failed to parse dictionary key

### ISSUE THREAD

**Issue by kevinswartz** [Hopding/pdf-lib#68] opened 2019-01-24 19:35 UTC
Hi @Hopding 
Got another pdf load error for you.  It's not a really useful pdf, but I thought you might want to look at it.  I'm on v0.6.1-rc2.  Thanks!

```
Error: Failed to parse dictionary key
    at error (pdf-lib.js:8569)
    at parseDict (pdf-lib.js:46630)
    at parseDictOrStream (pdf-lib.js:46908)
    at parseIndirectObj (pdf-lib.js:46947)
    at parseBodySection (pdf-lib.js:47174)
    at parseDocument (pdf-lib.js:47226)
    at PDFParser.parse (pdf-lib.js:47257)
    at Function.PDFDocumentFactory.load (pdf-lib.js:47379)
```

[giraffe.pdf](https://github.com/Hopding/pdf-lib/files/2793274/giraffe.pdf)

**Comment by Hopding** [comment] 2019-02-09 20:26
Hello @kevinswartz. 

Thanks for sharing this PDF. I took a look at it, and it is definitely corrupted. It's not a subtle corruption either. Among other things, a big chunk of bytes that should be present for one of the embedded image streams is totally gone. 

Do you happen to know how this PDF was generated? I'm wondering if it was generated in a corrupted state, or if it was a transmission error that caused the corruption.

Of course, it looks like most PDF viewers are able to open the document despite the corruption. I'll have to think about the best way for `pdf-lib` to handle this. Ideally, it would be able to fix the corrupted section. But this would require some nontrivial changes to the parsing logic. So I don't expect to work on this in the near-term.

As I understand it, this isn't causing any production issues for you. So I won't prioritize working on this. Please let me know if I misunderstood what you were saying.

**Comment by Hopding** [comment] 2019-02-09 21:09
@kevinswartz After investigating the other 3 issues you filed (#69, #70, and #73), it appears that you're dealing with an impressive number of corrupted/invalid PDFs. I mentioned that this PDF (the giraffe one) didn't seem to be a production issue, so I wouldn't prioritize work on this. But I assume the other 3 PDFs are causing production issues for you? Please let me know if this is the case, so I can prioritize work on this over other `pdf-lib` enhancements if necessary.

**Comment by kevinswartz** [comment] 2019-02-13 01:23
Hi @Hopding ,
You're right, this, and issue #69 are non-production problems.  I'm just about to email you the pdf for #70 .  This pdf and the one in #69 were generated in Adobe Acrobat Pro for windows.  #73 is a little different and I put a note in there about it.

**Comment by Hopding** [comment] 2019-02-24 19:34
Hello again @kevinswartz.

I implemented a fix for #70. I plan to work on #73 next.

Is there a particular set of steps you took to generate the PDFs from #68 and #69? I've generated a few PDFs in Adobe Acrobat Pro for Mac, and have been unable to reproduce either of these issues.

**Comment by kevinswartz** [comment] 2019-02-25 16:34
Hi @Hopding,
When I generated pdfs for #68 and #69 I was kind of just hacking around.  I saw the error with embedded pdfs in #70 and was just doing more testing with them.  It was all using Adobe Acrobat on windows, and FWIW it didn't seem to happen every time.  Sorry, I know that's probably not very helpful.

**Comment by Hopding** [comment] 2019-03-09 23:42
No worries. Thanks for the info. 

I'm going to close this issue for now since it isn't causing any production issues, and the error seems to be caused by a corrupted document.

**Closed by Hopding** 2019-03-09 23:42 UTC
Labels: corrupt-pdf
