### ISSUE TITLE
getPageCount returns undefined

### ISSUE THREAD

**Issue by gonuit** [Hopding/pdf-lib#150] opened 2019-07-30 18:31 UTC
After updating pdf-lib to 1.0.0 I'm unable to get pages count

**Comment by Hopding** [comment] 2019-08-01 11:22
Hello @gonuit!

I’ll need more to work from in order to help you with this. Can you please share some sample code that I can use to reproduce the issue? And, if you are loading existing PDFs, can you please share a sample PDF that you’re unable to get the page count for?

**Comment by Narigo** [comment] 2019-08-04 09:28
Here is some code and a PDF to reproduce:
```
#!/usr/bin/env node

const fs = require("fs");
const pdfLib = require("pdf-lib");

const pdfPath = process.argv[2];

run({ pdfPath }).catch(error => {
  console.log("Error running pdf-document-feeder", error);
});

async function run({ pdfPath }) {
  const pdfDocument = fs.readFileSync(pdfPath);
  const resultDoc = await pdfLib.PDFDocument.create();
  const doc = await pdfLib.PDFDocument.load(pdfDocument);
  const pageCount = await doc.getPageCount();
  console.log("pageCount =", pageCount);
}
```

The mentioned PDF = [test-input.pdf](https://github.com/Hopding/pdf-lib/files/3464743/test-input.pdf)

Run it with `node test.js test-input.pdf`.

---
I think this might be the underlying issue I'm fighting with when trying to update [my project](https://github.com/compose-us-research/pdf-document-feeder). Over there I get errors when using `insertPage` or `addPage` and it complains about error indices out of bounds.

**Comment by Narigo** [comment] 2019-08-04 09:59
@gonuit as a workaround, `doc.getPages().length` should still work to get the amount of pages in a document. (It doesn't really help for my case though, because adding and inserting seems to still have issues with using the internal page count...)

**Comment by Hopding** [comment] 2019-08-04 13:39
@Narigo Thanks for sharing the code sample and PDF to reproduce the issue. I was able to find the bug that is causing `getPageCount()` to return `undefined`. I'll get this fixed and release `v1.0.1` today. 

However, I've been unable to reproduce any errors about indices being out of bounds on `addPage`/`removePage`/`insertPage`. Is the error you're encountering similar to #149? If so, would you mind sharing steps to reproduce the issue over there?

**Comment by Narigo** [comment] 2019-08-04 14:01
@Hopding thanks for looking into it! :)

https://github.com/compose-us-research/pdf-document-feeder/blob/update-pdf-lib/src/index.js

This is the code I'm trying to get to run. In the repository itself is a test file `test-input.pdf` which should result in `test-expected.pdf` - if you run `npm run test`, it runs the code above, creates a temporary file `test-output.pdf` and then should check if the output matches the expected. Right now, it yields the following error:

```
$ node src/index.js test-input.pdf 
Error! Error: Index out of bounds: 6/6
    at PDFPageTree.insertLeafNode (/Users/joern/git/work/compose.us/pdf-document-feeder/node_modules/pdf-lib/cjs/core/structures/PDFPageTree.js:50:23)
    at PDFCatalog.insertLeafNode (/Users/joern/git/work/compose.us/pdf-document-feeder/node_modules/pdf-lib/cjs/core/structures/PDFCatalog.js:23:43)
    at PDFDocument.insertPage (/Users/joern/git/work/compose.us/pdf-document-feeder/node_modules/pdf-lib/cjs/api/PDFDocument.js:294:38)
    at run (/Users/joern/git/work/compose.us/pdf-document-feeder/src/index.js:20:9)
```

I've tried to use `addPage` as well instead of inserting on the last page but that did not work as well. I guess that most of these things might be related to the `pageCount`...

**Comment by Hopding** [comment] 2019-08-04 14:31
Thanks! I was able to reproduce the issue using your code. Now I can start working on getting it fixed.

**Comment by Hopding** [comment] 2019-08-04 14:48
@Narigo I ran your code after fixing the bug causing `getPageCount()` to return `undefined`. This resulting in a different (more understandable) error message:
```js
{ pageCount: 6, insertingAt: 1 }
{ pageCount: 6, insertingAt: 3 }
{ pageCount: 6, insertingAt: 5 }
{ pageCount: 6, insertingAt: 7 }
(node:53878) UnhandledPromiseRejectionWarning: Error: `index` must be at least 0 and at most 5, but was actually 7
    at Object.exports.assertRange (pdf-lib/scratchpad/build/src/utils/validators.js:105:15)
    at PDFDocument.insertPage (pdf-lib/scratchpad/build/src/api/PDFDocument.js:284:17)
    at Object.<anonymous> (pdf-lib/scratchpad/build/scratchpad/index.js:24:25)
    at step (pdf-lib/node_modules/tslib/tslib.js:136:27)
    at Object.next (pdf-lib/node_modules/tslib/tslib.js:117:57)
    at fulfilled (pdf-lib/node_modules/tslib/tslib.js:107:62)
```

I added a log statement to track how many pages the document has, and at what index the insertion is being performed:
```js
const amountOfPages = doc.getPages().length;
const lastPageIndex = amountOfPages - 1;
for (let i = 0; i < amountOfPages / 2; i++) {
  const pages = doc.getPages();
  const lastPage = pages[lastPageIndex];
  doc.removePage(lastPageIndex);
  console.log({ pageCount: doc.getPageCount(), insertingAt: i * 2 + 1 });
  doc.insertPage(i * 2 + 1, lastPage);
}
```

As you can see, the loop is trying to insert a page at index `7` despite the document only having 6 pages (meaning the highest valid insertion index is `5`). So the error here is correct. Of course, it was difficult to understand before the `undefined` page count issue was fixed.

You can fix the issue in your loop by changing the termination condition to the following:
```js
for (let i = 0; i < lastPageIndex / 2; i++) {
```

-----

So it looks like the only issue here is the undefined page count problem. The other error was a hard to find off-by-1 error in your loop code. Please let me know if this makes sense (or if you disagree). I'll work on getting v1.0.1 released with the undefined page count fix.

**Comment by Hopding** [comment] 2019-08-04 17:57
@gonuit @Narigo 

I just released v1.0.1 with the fix. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.0.1).

You can install it with `npm`:
```
npm install --save pdf-lib@1.0.1
```
or yarn:
```
yarn add pdf-lib@1.0.1
```
It's also available on the unpkg CDN:
* https://unpkg.com/pdf-lib@1.0.1/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@1.0.1/dist/pdf-lib.min.js

**Closed by Hopding** 2019-08-04 17:57 UTC

**Comment by Narigo** [comment] 2019-08-04 20:12
Very nice @Hopding - it works now!

Regarding the off-by-one error, this was actually intended in my code: It let me insert a page after the end of the document to add a page. Now I have to use `addPage` if I want to insert a new page at the end of the document. It's okay for me that way, but it's a bit strange that it worked before 1.0.0. Maybe you want to insert that in the "Migration" part of the docs then :)

**Comment by Hopding** [comment] 2019-08-04 21:29
Yes, you’re correct, v1.0.0 did allow indices to exceed the page count. It is definitely worth adding to the migration section of the README. Would you happen to be interesting in adding it? If not, I will. But you’ve got a better perspective than I do, having run into the problem yourself.

Also, instead of `addPage`, you can call `insertPage(pdfDoc.getPageCount(), ...)`. This is actually what `addPage()` does under the hood. For example, you could do this for your use case:
```js
doc.insertPage(
  Math.min(i * 2 + 1, doc.getPageCount()), 
  lastPage,
);
```
