### ISSUE TITLE
extract images from pdf

### ISSUE THREAD

**Issue by gihanrangana** [Hopding/pdf-lib#1081] opened 2021-11-09 07:57 UTC
### What were you trying to do?

i tried to extract image from pdf with version 0.6.0. but some images doesn't have mime types.
now i tried with latest version.but it's deferent than v0.6.0. i have no idea how to upgrade 0.6.0 code to latest 

### How did you attempt to do it?

i tried below way on 0.6.0

### What actually happened?

can't find mime from buffer

### What did you expect to happen?

want to update 0.6.0 code to latest 

### How can we reproduce the issue?

```
const pdf = await PDFDocumentFactory.load(doc);

    let objIdx = 0;

    pdf.index.index.forEach((pdfObject,ref) => {

        if (!(pdfObject instanceof PDFRawStream)) return;

        const { lookupMaybe } = pdf.index;
        const { dictionary } = pdfObject;

        const subtype = lookupMaybe(dictionary.getMaybe('Subtype'));

        if (subtype === PDFName.from('Image')) {

            objIdx++;
            var buffer = Buffer.from(pdfObject.content);

            try {

                console.log(await FileType.fromBuffer(pdfObject.content));

                var image = await Jimp.read(buffer);

                // console.log(buffer);
                image.writeAsync(`./output/${objIdx.toString()}.jpg`);

            } catch (e) {
                // console.log(buffer);
                console.log([objIdx, e.message]);
            }

        }

    })

```

### Version

latest

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by gihanrangana** [comment] 2021-11-09 08:13
on latest version i have tried like this
```
const pdf = await PDFDocument.load(doc);

    let objIdx = 0;

    pdf.context.indirectObjects.forEach((pdfObject,ref) => {

        if (!(pdfObject instanceof PDFRawStream)) return;

        objIdx++;
        var buffer = Buffer.from(pdfObject.contents);

        try {

            console.log(await FileType.fromBuffer(pdfObject.contents));

            var image = await Jimp.read(buffer);

            // console.log(buffer);
            image.writeAsync(`./output/${objIdx.toString()}.jpg`);

        } catch (e) {
            // console.log(buffer);
            console.log([objIdx, e.message]);
        }

    })

```

response 
![image](https://user-images.githubusercontent.com/24897554/140886740-5698cae8-c5be-436b-9318-93ea984ce926.png)

**Comment by dcsline** [comment] 2021-11-15 19:20
I have also test your code sample, so i could reproduce the error.
The problem solver is to use an other approach: 
Jimp.read(buffer)
  .then(image => {
    // Do stuff with the image.
  })
  .catch(err => {
    // Handle an exception.
  });

Here now the code for my succefully test:
-----------------------------------------------------------------------------------------------------
var templ= 'existing.pdf';  //Solis5YrTest-2.pdf';  
    console.log("File:"+ templ);
    //my load statement
    const pdfDoc = await PDFDocument.load(fs.readFileSync(templ)); 
  let objIdx = 0;
  const enumeratedIndirectObjects = pdfDoc.context.enumerateIndirectObjects();
  enumeratedIndirectObjects.forEach(x => {
  //pdfDoc.context.indirectObjects.forEach((pdfObject,ref) => {  
  const pdfRef = x[0];
  const pdfObject = x[1];
  
    if (!(pdfObject instanceof PDFRawStream)) return;
  
    const { dict } = pdfObject;
    objIdx++;
    var buffer = Buffer.from(pdfObject.contents);
        try {
          (async () => {
              const img = await Jimp.read(buffer).then(function (image) {
              image.writeAsync(`${objIdx.toString()}.jpg`, Jimp.MIME_JPEG);
          }).catch(function (err) {
                //return Promise.reject(err);
              }); 
             
           })();    

        } catch (e) {
            // console.log(buffer);
            //console.log([objIdx, e.message]);
        }
    })  
-----------------------------------------------------------------------------------------------------------
Please notice, you must also define the mime type in the writeAsync statement. Attached you can found my test pdf document and the extracted image file
[existing.pdf](https://github.com/Hopding/pdf-lib/files/7541182/existing.pdf)
![6](https://user-images.githubusercontent.com/86070005/141841170-6e9f16a7-ef99-464f-ada3-e97457137295.jpg)
.

**Comment by gihanrangana** [comment] 2021-11-16 06:11
> I have also test your code sample, so i could reproduce the error. The problem solver is to use an other approach: Jimp.read(buffer) .then(image => { // Do stuff with the image. }) .catch(err => { // Handle an exception. });
> 
> ## Here now the code for my succefully test:
> var templ= 'existing.pdf'; //Solis5YrTest-2.pdf'; console.log("File:"+ templ); //my load statement const pdfDoc = await PDFDocument.load(fs.readFileSync(templ)); let objIdx = 0; const enumeratedIndirectObjects = pdfDoc.context.enumerateIndirectObjects(); enumeratedIndirectObjects.forEach(x => { //pdfDoc.context.indirectObjects.forEach((pdfObject,ref) => { const pdfRef = x[0]; const pdfObject = x[1];
> 
> ```
> if (!(pdfObject instanceof PDFRawStream)) return;
> 
> const { dict } = pdfObject;
> objIdx++;
> var buffer = Buffer.from(pdfObject.contents);
>     try {
>       (async () => {
>           const img = await Jimp.read(buffer).then(function (image) {
>           image.writeAsync(`${objIdx.toString()}.jpg`, Jimp.MIME_JPEG);
>       }).catch(function (err) {
>             //return Promise.reject(err);
>           }); 
>          
>        })();    
> 
>     } catch (e) {
>         // console.log(buffer);
>         //console.log([objIdx, e.message]);
>     }
> })  
> ```
> 
> Please notice, you must also define the mime type in the writeAsync statement. Attached you can found my test pdf document and the extracted image file [existing.pdf](https://github.com/Hopding/pdf-lib/files/7541182/existing.pdf) ![6](https://user-images.githubusercontent.com/86070005/141841170-6e9f16a7-ef99-464f-ada3-e97457137295.jpg) .

i fixed it on the web. on node it it's not working as expected. 
thanks

**Comment by dcsline** [comment] 2021-11-16 09:00
Why not on node??? This have it now tested - it's worked. Please check your Jimp version, i have tested with version 0.16.1. Attached my test code.
[node_app.zip](https://github.com/Hopding/pdf-lib/files/7544827/node_app.zip)

**Comment by Hopding** [comment] 2021-11-27 20:10
Closing as this is not a bug. Feel free to open a discussion if you'd like help converting code from an old version of pdf-lib to the current API! See also https://github.com/Hopding/pdf-lib/issues/83#issuecomment-487383843.

**Closed by Hopding** 2021-11-27 20:10 UTC
Labels: bug
