### ISSUE TITLE
 Error: Failed to parse PDF document (line:0 col:36 offset=18): No PDF header found

### ISSUE THREAD

**Issue by RutviBhatt27** [Hopding/pdf-lib#240] opened 2019-11-19 21:31 UTC
Hi @Hopding,
I am using pdf-lib in my Lightning Web Component (Salesforce)'s javascript controller. 
While using the copy pages functionality, I am getting these error  "Error: Failed to parse PDF document (line:0 col:36 offset=18): No PDF header found". I used the same code but I don't know what is wrong with my file.
Thanks,
Rutvi

**Comment by ArtisanCodesmith** [comment] 2019-11-20 01:09
I got it too lol:
![image](https://user-images.githubusercontent.com/9778998/69199946-90458680-0b31-11ea-91f6-8b3fd07e2f85.png)

This code does it in ..etc..parseHeader():
![image](https://user-images.githubusercontent.com/9778998/69199988-b539f980-0b31-11ea-9cd1-8e7eb98807da.png)

Remove line 94, re-run or what you're running and it'll not throw the error:
![image](https://user-images.githubusercontent.com/9778998/69200030-d7337c00-0b31-11ea-9966-96b8d8fe8b27.png)

Doesn't die here now,  (line 21 was never met before):
![image](https://user-images.githubusercontent.com/9778998/69200160-3d200380-0b32-11ea-9204-00eda530cceb.png)

Seems to work well, I'm using this shit too (thanks for making it creators), if I wasn't hammering hours in I'd do a PR sorry, just checked if others had the issue and saw this

Hope it helps :B

**Comment by ArtisanCodesmith** [comment] 2019-11-20 01:11
Also won't PR because it's not even a hot-fix I guess, just a temporary fuck-it for now if you're using this rn :P @RutviBhatt27

**Comment by Hopding** [comment] 2019-11-20 03:07
Hello @RutviBhatt27! I need more information in order to help you with this. I'll need some code samples at least. But it you can, a complete Node script and some PDFs that I can use to reproduce the issue would be ideal.

**Comment by RutviBhatt27** [comment] 2019-11-20 14:44
Hi @Hopding, 
I am using Lightning Web Component in my code so I didn't use any Node script. My code for the copy function is below. 
```
import { LightningElement,  wire } from 'lwc';
import pdflibResource from '@salesforce/resourceUrl/PDFLib';
import { loadScript } from 'lightning/platformResourceLoader';
import getPdf from '@salesforce/apex/pdflibPlayController.getPdf';

export default class pdflibPlay extends LightningElement {
    arrayOfArrayBuffer = [];

    @wire(getPdf)
    wireGetPdf({ error, data }){
        let versionData = [];
      //fetching my files from Salesforce's server 
        if (data) {
            this.pdfs = data;
            this.error = undefined;
            data.forEach(dt => {
                versionData.push(dt.VersionData)
            });
        } else if (error) {
            this.error = error;
            this.tasks = undefined;
        }
      //converting files into Unit8Array
        for(let i = 0; i < versionData.length; i++){
            let uint8Array = new TextEncoder("utf-8").encode(versionData[i]);
            this.arrayOfArrayBuffer.push(uint8Array);
        }
        this.method();
    }
    method() {
        loadScript(this, pdflibResource + '/pdf-lib.min.js')
            .then(() => {
                this.initializePdfLib();
            });
    }

    initializePdfLib = async () => {

         // Load a PDFDocument from each of the existing PDFs

            var arrBuuf = this.arrayOfArrayBuffer;
            console.log('---array of ArrayBuffer inside merge func---' + arrBuuf)

            // Create a new PDFDocument
            const pdfDoc = await PDFLib.PDFDocument.create()

            // These should be Uint8Arrays or ArrayBuffers
            // This data can be obtained in a number of different ways
            // In the browser, you could make a fetch() call and use res.arrayBuffer()
            const firstDonorPdfBytes = arrBuuf[0];
            const secondDonorPdfBytes = arrBuuf[1];
                
            const firstDonorPdfDoc = await PDFLib.PDFDocument.load(firstDonorPdfBytes)
            const secondDonorPdfDoc = await PDFLib.PDFDocument.load(secondDonorPdfBytes)
            console.log('----first pdf----',firstDonorPdfDoc, '----second pdf----', secondDonorPdfDoc);


            // Copy the 1st page from the first donor document, and
            // the 743rd page from the second donor document
            const [firstDonorPage] = await pdfDoc.copyPages(firstDonorPdfDoc, [0])
            const [secondDonorPage] = await pdfDoc.copyPages(secondDonorPdfDoc, [742])

            // Add the first copied page
            pdfDoc.addPage(firstDonorPage)

            // Insert the second copied page to index 0, so it will be the
            // first page in `pdfDoc`
            pdfDoc.insertPage(0, secondDonorPage)

            // Serialize the PDFDocument to bytes (a Uint8Array)
            const pdfBytes = await pdfDoc.save()

            console.log('---Merger Result----' + pdfBytes);
        };
```

**Comment by Hopding** [comment] 2019-12-16 16:33
Hello again @RutviBhatt27. My apologies for the delayed response.

After looking at the code you shared, I suspect the issue lies in one of the following places:

- I suspect that `dt.VersionData` does not actually contain the bytes for a PDF file. I think this is the most likely cause of the error you are seeing.
  ```js
  data.forEach((dt) => {
    versionData.push(dt.VersionData);
  });
  ```

- But if `dt.VersionData` does, in fact, contain data for a PDF then my next best guess is that something is going wrong in this block where you encode the data.
  ```js
  for (let i = 0; i < versionData.length; i++) {
    let uint8Array = new TextEncoder('utf-8').encode(versionData[i]);
    this.arrayOfArrayBuffer.push(uint8Array);
  }
  ```

Can you log the values that are being pushed to the `versionData` array? E.g.
```js
data.forEach((dt) => {
  console.log('Data:', dt.VersionData);
  versionData.push(dt.VersionData);
});
```

If you share the output of these logs, I can try to help you further.

**Comment by Hopding** [comment] 2019-12-21 22:12
I'm going to close this issue for now. But please feel free to reopen it if you are still having trouble!

**Closed by Hopding** 2019-12-21 22:12 UTC

**Comment by manikghaisdei** [comment] 2021-08-11 19:27
> Hi @Hopding,
> I am using Lightning Web Component in my code so I didn't use any Node script. My code for the copy function is below.
> 
> ```
> import { LightningElement,  wire } from 'lwc';
> import pdflibResource from '@salesforce/resourceUrl/PDFLib';
> import { loadScript } from 'lightning/platformResourceLoader';
> import getPdf from '@salesforce/apex/pdflibPlayController.getPdf';
> 
> export default class pdflibPlay extends LightningElement {
>     arrayOfArrayBuffer = [];
> 
>     @wire(getPdf)
>     wireGetPdf({ error, data }){
>         let versionData = [];
>       //fetching my files from Salesforce's server 
>         if (data) {
>             this.pdfs = data;
>             this.error = undefined;
>             data.forEach(dt => {
>                 versionData.push(dt.VersionData)
>             });
>         } else if (error) {
>             this.error = error;
>             this.tasks = undefined;
>         }
>       //converting files into Unit8Array
>         for(let i = 0; i < versionData.length; i++){
>             let uint8Array = new TextEncoder("utf-8").encode(versionData[i]);
>             this.arrayOfArrayBuffer.push(uint8Array);
>         }
>         this.method();
>     }
>     method() {
>         loadScript(this, pdflibResource + '/pdf-lib.min.js')
>             .then(() => {
>                 this.initializePdfLib();
>             });
>     }
> 
>     initializePdfLib = async () => {
> 
>          // Load a PDFDocument from each of the existing PDFs
> 
>             var arrBuuf = this.arrayOfArrayBuffer;
>             console.log('---array of ArrayBuffer inside merge func---' + arrBuuf)
> 
>             // Create a new PDFDocument
>             const pdfDoc = await PDFLib.PDFDocument.create()
> 
>             // These should be Uint8Arrays or ArrayBuffers
>             // This data can be obtained in a number of different ways
>             // In the browser, you could make a fetch() call and use res.arrayBuffer()
>             const firstDonorPdfBytes = arrBuuf[0];
>             const secondDonorPdfBytes = arrBuuf[1];
>                 
>             const firstDonorPdfDoc = await PDFLib.PDFDocument.load(firstDonorPdfBytes)
>             const secondDonorPdfDoc = await PDFLib.PDFDocument.load(secondDonorPdfBytes)
>             console.log('----first pdf----',firstDonorPdfDoc, '----second pdf----', secondDonorPdfDoc);
> 
> 
>             // Copy the 1st page from the first donor document, and
>             // the 743rd page from the second donor document
>             const [firstDonorPage] = await pdfDoc.copyPages(firstDonorPdfDoc, [0])
>             const [secondDonorPage] = await pdfDoc.copyPages(secondDonorPdfDoc, [742])
> 
>             // Add the first copied page
>             pdfDoc.addPage(firstDonorPage)
> 
>             // Insert the second copied page to index 0, so it will be the
>             // first page in `pdfDoc`
>             pdfDoc.insertPage(0, secondDonorPage)
> 
>             // Serialize the PDFDocument to bytes (a Uint8Array)
>             const pdfBytes = await pdfDoc.save()
> 
>             console.log('---Merger Result----' + pdfBytes);
>         };
> ```

Hi @RutviBhatt27 ,
Hope you are doing good!!
Just wanted to check if you found any solution to this!! I know its being long time you posted this.. but just if you remember anything.. though my problem is different than this.. but I am using PDF-lib too.. for which i am getting error as 'Cannot read property 'create' of undefined' 
Can you help me with this?

Many Regards,
Manik
