### ISSUE TITLE
Adding transparent PNG image falls behind the PDF form elements.

### ISSUE THREAD

**Issue by andazin** [Hopding/pdf-lib#35] opened 2018-10-08 16:30 UTC
When the .png transparent image is added to existing PDF Document with pdf form elements - it is rendered behind the pdf elements (like z-order problem). It should be possible to force any added image to be on top of all existing elements. I did it with iText (overlay) and it worked. Here is a piece of code I used to add image with pdf-lib:

const imgName = "Img_" + getUniqueNum();
      const [img, imgDims] = pdfDoc.embedPNG(imageUint8Array);

      let contentStream = pdfDoc.createContentStream(
        drawImage(imgName, {
          x: posLeft,
          y: posBottom,
          width: tagWidth,
          height: tagHeight
        })
      );

      const pages = pdfDoc.getPages();
      const page  = pages[pageIndex];

      page.addImageObject(imgName, img).addContentStreams(pdfDoc.register(contentStream)).normalizeCTM();

The resulting screenshot is attached.

Thanks, 
Andrei.

---------------------------------------------------------------------------------------------------------------------------------------
![screenshot from 2018-10-08 12-20-56](https://user-images.githubusercontent.com/1385960/46621535-b22ea600-caf5-11e8-9c29-6e67d4bc994c.png)

**Comment by Hopding** [comment] 2018-10-10 18:08
Hello @andazin. I'm not sure why this is happening. Are you able to share the document before and after modification with `pdf-lib`? If so, I can dig into this and try to figure out the cause, and how it might be fixed.

**Comment by andazin** [comment] 2018-10-12 01:42
Andrew.

Thank you for reaching out.

The attached are the original document and 2 others with transparent PNG
and non transparent JPEG inserted.

It is not unique to the only this one document, but also to the ones with
PDF form elements.

Please, let me know if you need some other samples or help - I am more than
happy to contribute to fixing this amazing library.

Thanks,
Andrei Razine.

**Comment by Hopding** [comment] 2018-10-17 15:31
@andazin I'm unable to find the PDFs you attached, either in my email inbox or on the GitHub thread itself. Did you perhaps forget to attach them? If you're sure you attached them, can you try leaving a comment directly on the GitHub website (instead of using email), and attaching the PDFs to that?

**Comment by andazin** [comment] 2018-10-20 17:19
[01-Original.pdf](https://github.com/Hopding/pdf-lib/files/2498375/01-Original.pdf)
[JPEG-Inserted.pdf](https://github.com/Hopding/pdf-lib/files/2498376/JPEG-Inserted.pdf)
[PNG-Inserted-01.pdf](https://github.com/Hopding/pdf-lib/files/2498377/PNG-Inserted-01.pdf)
[PNG-Inserted-02.pdf](https://github.com/Hopding/pdf-lib/files/2498378/PNG-Inserted-02.pdf)


I just added the Original PDF and the result of adding different images.

**Comment by Hopding** [comment] 2018-10-29 21:20
I'm going to close this for now. But, please feel free to reopen it if you're still interested! (I certainly am. I'm very curious how iText was able to accomplish this).

**Closed by Hopding** 2018-10-29 21:20 UTC

**Comment by nesk** [comment] 2020-03-24 17:58
>If your trying to fill out the form fields, there’s a better approach than applying images on top of them. I can provide an example of how to do this with pdf-lib.

I would really appreciate an example if you have some time.

**Comment by nesk** [comment] 2020-03-24 23:43
```js
function getAcroFields(pdfDoc) {
  if (!pdfDoc.catalog.get(PDFName.of('AcroForm'))) return [];
  const acroForm = pdfDoc.context.lookup(pdfDoc.catalog.get(PDFName.of('AcroForm')));

  if (!acroForm.get(PDFName.of('Fields'))) return [];
  const acroFields = pdfDoc.context.lookup(acroForm.get(PDFName.of('Fields')));

  return acroFields.array.map(field => pdfDoc.context.lookup(field));
}

function createPDFArray(array, pdfDoc) {
  return array.reduce((array, value) => {
    array.push(value)
    return array
  }, new PDFArray(pdfDoc.context))
}

function createPDFDict(dict, pdfDoc) {
  return Object.entries(dict).reduce((dict, [key, value]) => {
    dict.set(key, value)
    return dict
  }, PDFDict.withContext(pdfDoc.context))
}

function findAcroFieldByName(pdfDoc, name) {
  const acroFields = getAcroFields(pdfDoc)
  return acroFields.find((acroField) => {
    const fieldName = acroField.get ? acroField.get(PDFName.of('T')) : {}
    return !!fieldName && fieldName.value === name
  })
}

function fillAcroTextField(
  pdfDoc,
  acroField,
  fontObject,
  text,
  fontSize = 15,
) {
  const fieldRect = acroField.get(PDFName.of('Rect'))
  const fieldWidth = fieldRect.get(2).number - fieldRect.get(0).number
  const fieldHeight = fieldRect.get(3).number - fieldRect.get(1).number

  const appearanceStream = pdfDoc.register(
    PDFContentStream.of(
      createPDFDict({
        Type: PDFName.of('XObject'),
        Subtype: PDFName.of('Form'),
        BBox: createPDFArray([
          PDFNumber.of(0),
          PDFNumber.of(0),
          PDFNumber.of(fieldWidth),
          PDFNumber.of(fieldHeight),
        ], pdfDoc.context),
        Resources: createPDFDict({
          Font: createPDFDict({
            FontObject: fontObject
          }, pdfDoc.context)
        }, pdfDoc.context),
      }, pdfDoc.context),
      drawLinesOfText(text.split('\n'), {
        color: { type: ColorTypes.RGB, red: 0, green: 0, blue: 0 },
        font: 'FontObject',
        size: fontSize,
        rotate: degrees(0),
        xSkew: degrees(0),
        ySkew: degrees(0),
        x: 2,
        y: fieldHeight - 13,
        lineHeight: fontSize,
      })
    ),
  )

  acroField.set('V', PDFString.fromString(text))
  acroField.set('Ff', PDFNumber.of(1))
  acroField.set('AP', createPDFDict({ N: appearanceStream }, pdfDoc.context))
}

const fillInField = (fieldName, text, fontSize) => {
  const field = findAcroFieldByName(pdfDoc, fieldName)
  if (!field) throw new Error(`Missing AcroField: ${fieldName}`)
  fillAcroTextField(pdfDoc, field, StandardFonts.Helvetica, text, fontSize)
}

fillInField('Nom et prénom', 'Mario')
```

I've got to this point, it took quite some time, but now I'm stuck on this error:

```
TypeError: pdfDoc.register is not a function
```

I don't know how to replace the `register` function, to make the whole code work.

Also, could you tell me how to check a box please?

**Comment by Hopding** [comment] 2020-04-09 22:28
Hello @nesk!

It looks like the example you are referencing was created for an old version of pdf-lib. Here's an example that should work with the latest version of the library: https://github.com/Hopding/pdf-lib/issues/205#issuecomment-568938999

There should be some issues about toggling form field check boxes. Here's one I was able to dig up that might be helpful: https://github.com/Hopding/pdf-lib/issues/109#issuecomment-568484109

**Comment by nesk** [comment] 2020-04-10 06:57
Thank you @hopding!
