### ISSUE TITLE
Fields - Visible but doesn't print.

### ISSUE THREAD

**Issue by gregharkins** [Hopding/pdf-lib#603] opened 2020-09-15 18:58 UTC
When adding a text field all works as expected until trying to print or flatten the filled form. Looking at the properties of the form field in Acrobat, it's set to "Visible but doesn't print."

**Comment by Hopding** [comment] 2020-09-15 23:55
Hello @gregharkins! Thanks for reporting this. The issue is fixed in version [`1.11.1`](https://www.npmjs.com/package/pdf-lib/v/1.11.1). The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.11.1).

You can install this new version with npm:

```
npm install pdf-lib@1.11.1
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.11.1/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.11.1/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.11.1/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.11.1/dist/pdf-lib.min.js

**Closed by Hopding** 2020-09-15 23:55 UTC
