### ISSUE TITLE
after adding Qr Image, other image background became green.

### ISSUE THREAD

**Issue by jaypeevns** [Hopding/pdf-lib#89] opened 2019-04-01 13:37 UTC
Hi Andrew,

I am having a pdf in which we already have three images. Now I need to attach a QR code in it. when I am doing it pragmatically , I am getting green background on result pdf.

I am attaching before and after snapshot of pdf.

Please help us to resolve this issue.

Regards,
jay Prakash Verma
<img width="163" alt="beforeQREmbed" src="https://user-images.githubusercontent.com/8035432/55331588-3b290780-54b1-11e9-9450-12583dbfd616.png">
<img width="170" alt="afterQrEmbed" src="https://user-images.githubusercontent.com/8035432/55331641-53992200-54b1-11e9-94c7-f5a8ec8be9d8.png">

**Comment by Hopding** [comment] 2019-04-01 13:57
@jaypeevns Can you please share the code you are using to add the QR Code? Also, if you're able to provide the original PDF, that would help me to reproduce the issue.

**Comment by jaypeevns** [comment] 2019-04-01 15:22
Hi Andrew,

I can provide you the code but I can't give you pdf. in the pdf we are having 3 images and we are adding one qr code png in it.

var { PDFDocumentFactory, PDFDocumentWriter, drawImage} = require('pdf-lib');
    var fs = require('fs');
    var qr_pdf_bytes ={};
    qr_pdf_bytes.pdfBytes = fs.readFileSync("location of file pdf");
    qr_pdf_bytes.qrBytes= fs.readFileSync("location of QR code png");
    var QRCode_PNG = 'QRCodePng';
    var pdfDoc = PDFDocumentFactory.load(qr_pdf_bytes.pdfBytes);
    var [QRCodePngRef, QRCodePngDims] = pdfDoc.embedPNG(qr_pdf_bytes.qrBytes);
    var pages = pdfDoc.getPages();
    var existingPage = pages[0]
        .addImageObject(QRCode_PNG, QRCodePngRef);
    var newContentStream = pdfDoc.createContentStream(
        drawImage(QRCode_PNG, {
            x: parseInt("55"),
            y: parseInt("65"),
            width: 50,
            height: 50,
        })
    );
    existingPage.addContentStreams(pdfDoc.register(newContentStream));
    qr_pdf_bytes.pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);

**Comment by Crunchyalex** [comment] 2019-04-02 07:00
I've had a very similar issue, but in my case the problem seems to derive from the compression level of a pdf file. 
![Compression example](https://user-images.githubusercontent.com/18145506/55382306-a44a6280-5525-11e9-9b32-82aded882db0.png)

If you have a compressed pdf, some illustrations become very glitchy and odd. Whereas uncompressed pdf's turn out just fine.
Without manipulating the pdf's, just loading and unloading them, this seems to occur every time.

I've personally resolved the issue by avoiding pdf compression.

**Comment by Hopding** [comment] 2019-04-02 15:15
@Crunchyalex Nearly all PDF documents contain compressed data. And thus far, I've been unable to produce a similar result on any PDF I've tested. Can you please clarify what you mean by "compressed pdf"?

Also, would you happen to have a sample PDF I can use to reproduce the issue? I don't think I'll be able to resolve this issue very quickly without access to a PDF I can test on. Or, alternatively, a way that I can generate such a PDF.

**Comment by jaypeevns** [comment] 2019-04-03 08:15
Hi Andrew,

I am attaching the template where we are facing issue. please attach any qr image on it and help me if you are able to replicate the issue.
[beforeQREmbed.pdf](https://github.com/Hopding/pdf-lib/files/3037543/beforeQREmbed.pdf)

**Comment by jaypeevns** [comment] 2019-04-10 06:51
Hi andrew,

Please let me know if you are able to replicate the issue.

**Comment by Hopding** [comment] 2019-04-10 23:00
Hello @jaypeevns. I've been swamped with work and school lately. I'm afraid I haven't had a chance to look any further into this yet. I'll let you know as soon as I do. Hopefully within the next two weeks.

**Comment by jaypeevns** [comment] 2019-04-15 12:22
Thanks Andrew, I am eagerly waiting your reply.

**Comment by Hopding** [comment] 2019-04-28 19:09
Hello @jaypeevns! I finally got some time to investigate this today.

The cause of this issue was several invalid strings being produced by `pdf-lib`. Basically, `pdf-lib` was escaping `\`, `(`, and `)` characters in `PDFString` objects when it should not have been.

Anyways, I was able to fix this in https://github.com/Hopding/pdf-lib/pull/100. With these changes, everything works smoothly, and the three images in your PDF no longer have green backgrounds.

I just cut prerelease [`0.6.2-rc2`](https://www.npmjs.com/package/pdf-lib/v/0.6.2-rc2) with the fix.

You can install this prerelease with npm:
```
npm install pdf-lib@0.6.2-rc2
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.6.2-rc2/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.6.2-rc2/dist/pdf-lib.min.js

Please try it out and let me know if it works for you! 

@Crunchyalex I'd be grateful if you'd test this out as well.

**Comment by Crunchyalex** [comment] 2019-04-30 07:59
I've tested it with the exact same pdf as before, and it doesn't produce the same artifact on your prerelease build! 
Thank you for resolving this. 
And for keeping this library up and healthy! It's very useful!

**Comment by Hopding** [comment] 2019-05-05 00:37
Version [`0.6.2`](https://www.npmjs.com/package/pdf-lib/v/0.6.2) is now published. It contains fix for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.6.2).

You can install this new version with npm:
```
npm install pdf-lib@0.6.2
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.6.2/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.6.2/dist/pdf-lib.min.js

**Closed by Hopding** 2019-05-05 00:37 UTC
