### ISSUE TITLE
PDF optimization

### ISSUE THREAD

**Issue by frandiox** [Hopding/pdf-lib#54] opened 2018-12-17 03:00 UTC
Hi! First of all, thanks a lot for this library.

I'd like to ask if you are planning on adding PDF optimization at some point. When I print a PDF with Acrobat, it processes the PDF for about 5 seconds (optimizing, flattening...) and then sends it to the printer quite fast. On the other hand, when I send the same PDF to the printer directly from the browser it takes a surprisingly large amount of time (without optimizations, I assume).

I've seen in the roadmap something like ` Consider detecting and removing duplicate objects to reduce file size` but I'm not sure if that would improve printing time or it mostly depends on something else. Otherwise, if this is out of the scope of this library, would you have any pointers that could help speed up printing time?
Thansk again!

**Comment by frandiox** [comment] 2018-12-21 04:01
@Hopding I just sent you an email with PDF samples.
I tried `useObjectStreams: false` but the time didn't change much (1-2 seconds). The file size increased a little bit, though.

Under the same conditions, Acrobat was printing them about 10-15 seconds faster. We tried with 2 different printers and both had similar outputs.
Thank you!

**Comment by Hopding** [comment] 2018-12-23 23:09
Thanks for sending over those sample documents Fran. 

I took a look at the sizes of the `sample-long.pdf` and `sample-short.pdf` files before and after saving/exporting them in Acrobat:

| Name                     | Size   | Space Saved |
|--------------------------|--------|-------------|
| sample-short.pdf         | 161 KB |             |
| sample-short-acrobat.pdf | 160 KB | 0.62%       |
| sample-long.pdf          | 390 KB |             |
| sample-long-acrobat.pdf  | 379 KB | 2.82%       |

You can see that Acrobat does save a few KBs in its exports. But these saving are pretty minimal. 

I was wondering if the reason Acrobat was printing so much faster was because it removed duplicate objects from its input PDF. [A few months ago](https://github.com/Hopding/pdf-lib/issues/9#issuecomment-413407284) I helped a user of `pdf-lib` investigate why Acrobat was able to output PDFs that were several hundred KBs smaller than those output by `pdf-lib`. The reason turned out to be that the document being fed into `pdf-lib` contained hundreds of duplicate objects (a problem with the SVG tool he was using). However, I no longer think duplicate objects are causing your printing issues, because the difference before/after saving in Acrobat is just a few KBs, not several hundred.

I opened up the four documents listed in the table above in a text editor. I noticed that the two documents saved by Acrobat are both linearized, while the other two are not linearized. Linearized PDFs are specially formatted PDF files that are optimized for rendering the first page(s) of a PDF before the whole thing has finished streaming over the network. (See the end of this comment for an excerpt from the [PDF spec](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) describing linearized PDFs). 

I'm wondering if the reason PDFs print so much faster from Acrobat is because they are linearized by Acrobat before being sent to the printer. This might allow the printer to start printing before it has received and processed the entire file. (This effect would be exacerbated if the network is slow).

Of course, it's also possible that the issue lies somewhere in the browser. Perhaps printing _any_ PDF from the browser would be slower than doing so from Acrobat. To help me figure out if Linearization is the real issue here, can you please perform the following 4 test cases:

1. Load the `sample-short.pdf` into your browser (without being processed by `pdf-lib` or Acrobat) and see how long it takes to print.
2. Load the `sample-short.pdf` into your browser and run it through `pdf-lib`, then see how long it takes to print.
3. Save the `sample-short.pdf` in Acrobat and load the resulting PDF into your browser, then see how long it takes to print.
4. Save the `sample-short.pdf` in Acrobat and see how long it takes to print (from Acrobat, not from your browser).
-----

Excerpt from the PDF specification on linearized PDFs:

> **Annex F**
> **Linearized PDF**
> 
> Linearization of PDF is an optional feature available beginning in PDF 1.2 that enables efficient incremental access of the file in a network environment. Enhanced conforming readers can recognize that a PDF file has been linearized and may take advantage of that organization to enhance viewing performance.
>
> The primary goal for a linearized PDF file is to achieve the following behavior for documents of arbitrary size and so that the total number of pages in the document should have little or no effect on the user-perceived performance of viewing any particular page:
> 
> * When a document is opened, display the first page as quickly as possible. The first page to be viewed may be an arbitrary page of the document, not necessarily page 0 (though opening at page 0 is most common).
> * When data for a page is delivered over a slow channel, display the page incrementally as it arrives. To the extent possible, display the most useful data first.

**Comment by frandiox** [comment] 2018-12-24 03:52
Thanks for your prompt answer! It could be indeed related to printing from the browser rather than PDF optimization. Searching for this issue I've found some users complaining about their printers taking even minutes to print the first page, which sounds very similar to my scenario 🤔 

Perhaps linearizing the PDF could help but, unfortunately, I won't be able to test this in the next month since I have no printers around anymore 😓 

I've read something about "print-as-image" and using PS drivers instead of PCL. I'm not very familiarized with PDF and printer drivers but I guess I could also try that.

Again, thank you very much for checking this!

**Comment by Hopding** [comment] 2018-12-27 22:00
Hmm, okay. Well, I'm going to close this issue for now under the assumption that the issue is printing from the browser. Of course, if we can demonstrate that the long print times are due to the PDFs produced by `pdf-lib`, then I'm more than happy to reopen this. If you have a chance to do some testing when you gain access to more printers, please let me know what you find!

**Closed by Hopding** 2018-12-27 22:00 UTC
