### ISSUE TITLE
[Feature Request] Support for PDF/A

### ISSUE THREAD

**Issue by endevo-mschulz** [Hopding/pdf-lib#683] opened 2020-11-23 10:18 UTC
Hi,
it would be awesome to have the option to add PDF/A ccompliance to the created PDF-document.

When I open a PDF with pdf-lib and copy the pages, it is not PDF/A standard anymore, even with no changes.

**Comment by Hopding** [comment] 2020-11-24 00:39
Hello @endevo-mschulz! This looks like a duplicate of https://github.com/Hopding/pdf-lib/issues/230. Note also that @DkDavid is working on a PR to improve PDF/A compliance: https://github.com/Hopding/pdf-lib/pull/508.

**Closed by Hopding** 2020-11-24 00:39 UTC
